export const CHANGE_MENU_TAB = "CHANGE_MENU_TAB";

export const ACTIONS_OF_POPUP = {
  OPEN_LOGIN_POPUP: "OPEN_LOGIN_POPUP",
  OPEN_REGISTER_POPUP: "OPEN_REGISTER_POPUP",
  CLOSE_POPUP: "CLOSE_POPUP",
};

export const ACTIONS_OF_BOOKING = {
  CHANGE_START_DATE: "CHANGE_START_DATE",
  CHANGE_END_DATE: "CHANGE_END_DATE",
  CHANGE_GUESTS: "CHANGE_GUESTS",
  CHANGE_NIGHTS: "CHANGE_NIGHTS",
};

export const ACTIONS_OF_USER = {
  USER_INFO_RECEIVED: "USER_INFO_RECEIVED",
  CHANGE_AVATAR: "CHANGE_AVATAR",
  LOGOUT: "LOGOUT",
};
